spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100  #配置最大池大小
      auto-commit: true     #配置从池返回的连接的默认自动提交行为
      idle-timeout: 300000    #允许连接在连接池中空闲的最长时间（以毫秒为单位）
      max-lifetime: 1200000 #maxLifetime是池中连接关闭后的最长生命周期（以毫秒为单位）
      minimum-idle: 5   #HikariCP在连接池中维护的最小空闲连接数
      connection-test-query: SELECT 1
    dbcp2:
      time-between-eviction-runs-millis: 18800   # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      test-on-borrow: false
      test-while-idle: true
      initial-size: 5
    #url: jdbc:mysql://rm-uf6t4fk7e44o771zzco.mysql.rds.aliyuncs.com:3306/zdyx?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
    #username: zhengdao
    #password: '!@#12312$%^&*()321312ASDASD_+-='
    url: jdbc:mysql://47.101.32.137:3306/zdyx-dev?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: npi@12345

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
